### ISSUE TITLE
Đây là tiêu đề của thằng editor nè

### ISSUE THREAD

**Issue by trungtin2qn1** [nguyenhuutukhtn/ptudweb_thnews#1]
Sau đó chỗ này m cho nó nhập content

Rồi m cho nó up hình lên trên này bằng cái dòng attach files đó m thấy không :||||||||

![Kim-Yoo-jung_ (1)](https://user-images.githubusercontent.com/33853321/59185666-36f92480-8b9b-11e9-95d0-53a34cd33aac.jpg)

Và bây giờ m lưu hết cái đám này vào trong db (content)

Xong! Lúc sau m chỉ cần load lên trên 1 cái div nào đó là ok thấy nó ez không :))

**Comment by nguyenhuutukhtn** [comment]
sdsdads
**jjhhj**
_sfd_
